### ISSUE TITLE
Renaming of `iceoryx_utils` to `iceoryx_hoofs`

### ISSUE THREAD

**Issue by dkroenke** [ros2-gbp/iceoryx-release#2]
Hello,
we have renamed one of our packages that contain the basic building blocks for building iceoryx.
More precisely, the `iceoryx_utils` package (integrated in Galactic and Rolling) was renamed to `iceoryx_hoofs` which stands for ["Handy Objects Optimised For Safety"](https://github.com/eclipse-iceoryx/iceoryx/tree/master/iceoryx_hoofs)

This change has no immediate effect on ROS Rolling (and Galactic), since [ros2.repos](https://github.com/ros2/ros2/blob/9597c36591c643a1ff6d87964ddd3d999f191baf/ros2.repos#L49) is tied to a release branch where the changes are not applied.
We plan to update iceoryx to a newer release branch for ROS 2 Humble where this change would then come with.

The question is, how the packaging of ROS 2 will deal with it. 
We have this entry here that needs to be adapted for the rosdistro PR by bloom: https://github.com/ros/rosdistro/blob/d9d50be8f60de1bc7085916684066eb7f82e5ae6/rolling/distribution.yaml#L1195
Is there anything else that needs to be considered? (Beside the update in ros2.repos)
What happens with the old `iceoryx_utils`? Will it just stay or be removed?

**Comment by clalancette** [comment]
> The question is, how the packaging of ROS 2 will deal with it.
> We have this entry here that needs to be adapted for the rosdistro PR by bloom: https://github.com/ros/rosdistro/blob/d9d50be8f60de1bc7085916684066eb7f82e5ae6/rolling/distribution.yaml#L1195
> Is there anything else that needs to be considered? (Beside the update in ros2.repos)
> What happens with the old `iceoryx_utils`? Will it just stay or be removed?

As far as I understand, it will be removed.  There may need to be some manual cleanup on the buildfarm to actually remove the jobs from building the old package, but that has no effect other than wasting some slots on the buildfarm.  @nuclearsandwich Can chime in here to correct me if I'm wrong.

**Comment by nuclearsandwich** [comment]
When generating the pull request for the first release which includes iceoryx_hoofs, bloom will update the package list removing iceoryx_utils in the process since that package is no longer present in the upstream repository.

As the release propagates through the build farm. the iceoryx_utils job will be deleted as an obsolete job. However, the iceoryx utils package itself won't be removed from the package repositories by any direct action. Instead it will persist as a zombie package until one of its dependencies gets rebuilt. The rebuild of that dependency package will trigger a purge and rebuild of its downstream but since iceoryx_utils is no longer a valid package it will not be rebuilt.

It may be worth adding [`<conflict>`](https://www.ros.org/reps/rep-0149.html#conflict-multiple) and [`<replace>`](https://www.ros.org/reps/rep-0149.html#replace-multiple) tags for iceoryx_utils to the package.xml. They're not used much in the ROS ecosystem but this is exactly the use case for them.

> This change has no immediate effect on ROS Rolling (and Galactic), since [ros2.repos](https://github.com/ros2/ros2/blob/9597c36591c643a1ff6d87964ddd3d999f191baf/ros2.repos#L49) is tied to a release branch where the changes are not applied.
> We plan to update iceoryx to a newer release branch for ROS 2 Humble where this change would then come with.

I would strongly recommend making this change _in_ Rolling well before the Humble release and probably before the [rmw feature freeze](https://discourse.ros.org/t/upcoming-rmw-feature-freeze-for-humble-on-march-21th/24610) on 2022-03-21 since iceoryx_utils is a dependency of cyclonedds.

Rolling is distributed with this kind of volatility in mind. We don't include comprehensive changelogs for Rolling syncs but you could comment on either the preparation thread or the sync announcement with this change when it gets added in order to make it visible to those who may be using the package outside the public build farm and don't read the individual release PR changelogs.

**Comment by dkroenke** [comment]
@nuclearsandwich 
thanks for the helpful input. 
Regarding the `<conflict>` and `<replace>` tags, after some reading and testing I'm not 100% sure if the buildfarm will deal correctly with it.

I added it like this to the new package.xml:

```xml
    <conflict>iceoryx_utils</conflict>
    <replace>iceoryx_utils</replace>
```

The conflict tag can be maybe discussed, since the new versions of iceoryx/cyclonedds only link to `iceoryx_hoofs`.
I'm still a bit hesitant to add these tags because with them, I cannot build a local debian package anymore:

```bash
foo@bar:~/ros2_rolling/src/eclipse-iceoryx/iceoryx/iceoryx_hoofs$ bloom-generate rosdebian
==> Generating debs for ubuntu:focal for package(s) ['iceoryx_hoofs']
ROS Distro index file associate with commit 'c3ece5df69eeae8faa3d3348f6fbfd6baad093b0'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/c3ece5df69eeae8faa3d3348f6fbfd6baad093b0/index-v4.yaml'
GeneratorError: Error running generator: Failed to resolve rosdep key 'iceoryx_utils', aborting.
```

We are aware that updates like this should happen before the rmw freeze. We are currently working together with cyclonedds to integrate and test everything together.
CC @budrus

**Comment by nuclearsandwich** [comment]
> , after some reading and testing I'm not 100% sure if the buildfarm will deal correctly with it.

That's entirely possible. The buildfarm _should_ be able to deal with these package relationships but they're so rarely utilized I would not be surprised if this has bitrotted (or was never working in production to begin with).

If there are any files in-common between iceoryx_utils and iceoryx_hoofs such as transitional header files then you'll _need_ the `replace` declaration in order for apt to unpack iceoryx_hoofs on a system with iceoryx_utils already installed. 

According to the [documentation](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-replaces) `Replaces` and `Breaks` are the two that are strongly recommended to be used in conjunction but the package.xml format does not have an analogue to `Breaks`.

> I'm still a bit hesitant to add these tags because with them, I cannot build a local debian package anymore:

I have a sinking feeling that I know why this is happening and no good answer for what can be done about it, but I'll do some local testing and write back. Because we have at least one ground-up rebuild coming in Rolling as soon as we're through the woods on the python 3.10 transition the main case I want to make sure we are handling is the end user performing an apt-upgrade / dnf-upgrade.

**Comment by dkroenke** [comment]
@nuclearsandwich 
Thanks for the help.
Regarding common files between `iceoryx_utils` and `iceoryx_hoofs`, afaik there are no files shared between both packages.
The include path of the headers for changes then like this:

    ```cpp
    // before
    #include "iceoryx_hoofs/cxx/helplets.hpp"

    // after
    #include "iceoryx_hoofs/cxx/requires.hpp"
    ```

We created a PR in iceoryx to add these tags: https://github.com/eclipse-iceoryx/iceoryx/pull/1275, hope that is the correct way to add them.

Edit: We brought the `<conflict>` and `<replace>` tag into the new `iceoryx_hoofs` package.

**Comment by dkroenke** [comment]
@nuclearsandwich 

It seems that the ROS buildfarm is now facing conflicts with iceoryx v2.0.1:
- https://build.ros2.org/job/Rbin_ujv8_uJv8__iceoryx_posh__ubuntu_jammy_arm64__binary/10/console
- https://build.ros2.org/job/Rbin_uJ64__iceoryx_posh__ubuntu_jammy_amd64__binary/11/console

The log shows that the Buildfarm tries to install `iceoryx_utils` as dependency to `iceoryx_posh`, which is conflicting with `iceoryx_hoofs`. Are there maybe some build artifacts remaining that needs manual action?

Strange is that on march 29th, the first run with iceoryx v2.0.0 was fine and nothing changed regarding the package dependencies:
- https://build.ros2.org/job/Rbin_uJ64__iceoryx_posh__ubuntu_jammy_amd64__binary/9/

**Comment by nuclearsandwich** [comment]
Taking a look now. Thanks for raising the issue @dkroenke (and @clalancette for escalating the ping internally)

**Comment by nuclearsandwich** [comment]
Here is the issue:

https://github.com/ros2-gbp/iceoryx-release/blob/4225b35e35060ce07f5665b516fad128e0d7b989/debian/control#L5

Now I need to figure out how it ended up there.

**Comment by dkroenke** [comment]
> Here is the issue:
> 
> https://github.com/ros2-gbp/iceoryx-release/blob/4225b35e35060ce07f5665b516fad128e0d7b989/debian/control#L5
> 
> Now I need to figure out how it ended up there.

@nuclearsandwich 
A possible reason it is a mistake on my end, I tried locally to build the debian packages and maybe my local rosdep in `/etc/ros/rosdep/sources.list.d/20-default.list` got messed up...
I can clean this up and could try again to push a new version to `iceoryx-release` and then inspect the entry in `iceoryx-release/debian/control`. Does it make sense?

**Comment by nuclearsandwich** [comment]
So, locally with bloom 0.10.7 I ran `bloom-release -r rolling iceoryx --debug` (aside, I think there's something wrong `--pretend` as it did not actually seem to run the generators) and then when prompted to push the changes I broke out of the bloom release with ^Z and checked out the temporary directory I don't see the ros-rolling-iceoryx-utils dependency.

---

Since I've published iceoryx before, I'm going to make and push a package revision release in order to unblock the buildfarm but I want to make sure that this weird fluke isn't recurring for @dkroenke as well.

@dkroenke can you run the above command, and when prompted to push, do the following.

1. When prompted to push to the release repository, stop and use ^Z to pause bloom execution or open another terminal window.
2. Note the temporary directory used for the local bloom run. It will be shown in the bloom debug output, for example:
```
Checking out to master
Requested checkout reference is the same as the current branch
/tmp/tmph2d78vdr:$ git add README.md
/tmp/tmph2d78vdr:$ git commit -m "Updating README.md"
Checking out to master
Requested checkout reference is the same as the current branch
==> git remote -v
origin	ssh://git@github.com/ros2-gbp/iceoryx-release.git (fetch)
origin	ssh://git@github.com/ros2-gbp/iceoryx-release.git (push)
Releasing complete, push to release repository?
Continue [Y/n]?I want to 
```
The directory is `/tmp/tmph2d78vdr`

3. `cd /tmp/tmph2d78vdr`
4. Check whether `git show debian/rolling/jammy/iceoryx_posh:debian/control | grep iceoryx-utils` shows output (it will be the Build-Depend and/or Depend line from the debian/control file).
5. If the above shows output, can you copy the entire bloom debug log into a gist and send it to me. There shouldn't be anything sensitive, such as GitHub tokens in the log file but if you're concerned you can email it directly to me `steven@openrobotics.org`.

**Comment by nuclearsandwich** [comment]
I have pushed https://github.com/ros/rosdistro/pull/32659 which should unblock the builds for now. I am not considering the matter closed until we verify that this fluke isn't ongoing for @dkroenke and other iceoryx maintainers.

**Comment by dkroenke** [comment]
@nuclearsandwich Thanks for the support! After looking at the buildfarm it seems that the iceoryx packages are back to normal.

Here the generated output: https://gist.github.com/dkroenke/fa5d6a063398cc0ff24fac9dbf67db8b#file-bloom-release-fail-log
There is some output regarding debian deps when executing `git show debian/rolling/jammy/iceoryx_posh:debian/control | grep iceoryx-utils` in the tmp folder:
```console
Build-Depends: debhelper (>= 9.0.0), cmake, git, ros-rolling-iceoryx-hoofs, ros-rolling-iceoryx-utils, ros-rolling-ros-workspace
Depends: ${shlibs:Depends}, ${misc:Depends}, ros-rolling-iceoryx-hoofs, ros-rolling-iceoryx-utils, ros-rolling-ros-workspace
```

The reason for that is that my local rosdeps were messed up with a modification for building the iceoryx packages locally. To make this possible I need to tell rosdep which package to look for to make `bloom-generate` able to resolve the dependency.

After cleaning up my rosdep by removing `/etc/ros/rosdep/sources.list.d/20-default.list` and reinitializing rosdep with `init` and `update` the wrong entry in `debian/control` disappear.
Here another bloom log: https://gist.github.com/dkroenke/1dce6f8fd96c2efe85ba524479896f88#file-bloom-release-clean-rosdep-log

The only thing I'm wondering is a log output like this:
```
#### Generating 'bullseye' debian for package 'iceoryx_utils' at version '1.0.2-3'
```
Shouldn't utils not be ignored from now on?

**Comment by dkroenke** [comment]
@nuclearsandwich 
I did a new attempt on https://github.com/ros/rosdistro/pull/32724 by blooming an iceoryx bugfix release.
This time in a clean environment using [ros2-ade](https://gitlab.apex.ai/apex.ai-public/ros2-ade) and checked for iceoryx_utils dependency like mentioned in https://github.com/ros2-gbp/iceoryx-release/issues/2#issuecomment-1089304494.

For the case that the build fails i have saved the debug log.

**Comment by nuclearsandwich** [comment]
> I did a new attempt on [ros/rosdistro#32724](https://github.com/ros/rosdistro/pull/32724) by blooming an iceoryx bugfix release.

Great! I checked and the generated artifacts look sound. The modified rosdep context was definitely a contributing part of the problem. Bloom could do more to block "rosdep tomfoolery" but it's only tomfoolery when running releases targeting the official build farm.

**Comment by dkroenke** [comment]
> Great! I checked and the generated artifacts look sound. The modified rosdep context was definitely a contributing part of the problem. Bloom could do more to block "rosdep tomfoolery" but it's only tomfoolery when running releases targeting the official build farm.

@nuclearsandwich Bloom could may check this, but it's mainly up to the maintainer to ensure a clean rosdep environment before releasing a package, I created a comment here: https://github.com/ros2/ros2_documentation/pull/2375

I consider this ticket here as closed, thanks again for your great support!
